branches:
  only:
  - travis-ci
language: python
python:
  - 3.6
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database travisci;' -U postgres
  - python manage.py migrate
  - python manage.py loaddata mreg/fixtures/fixtures.json
script:
  - python manage.py test