branches:
  only:
  - travis-ci
language: python
python:
  - 3.6
services:
  - postgresql
addons:
  postgresql: "11"
before_script:
  - psql -c 'create database travisci;' -U postgres
  - python manage.py migrate
script:
  - python manage.py test